import Image from 'next/image'
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="es">
      <body>
         <header className='h-[15vh] bg-slate-100 overflow-hidden flex justify-center p-5'>
            <Image className='h-full' src="./logos/ping-pong-retics.svg" alt="logo" width={900} height={600}/>
         </header>
         {children}
         </body>
    </html>
  );
}
